#!/usr/bin/env python3
"""
Generate skills data for GitHub Pages
Scans all skill files and generates JavaScript data file

Usage:
    python scripts/generate_skills_data.py
"""

import re
import yaml
import json
from pathlib import Path
from typing import Dict, List, Optional

SCRIPT_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SCRIPT_DIR.parent
SKILLS_DIR = PROJECT_ROOT / 'skills'
OUTPUT_FILE = PROJECT_ROOT / 'assets/js/skills-data.js'

# Category icons mapping
CATEGORY_ICONS = {
    'executive': '👔',
    'software': '💻',
    'technology': '🔧',
    'ai-ml': '🤖',
    'healthcare': '⚕️',
    'medical': '🏥',
    'legal': '⚖️',
    'education': '🎓',
    'finance': '💰',
    'creative': '🎨',
    'research': '🔬',
    'product': '📦',
    'marketing': '📊',
    'automotive': '🚗',
    'data': '🗄️',
    'business': '💼',
    'construction': '🏗️',
    'manufacturing': '🏭',
    'energy': '⚡',
    'aerospace': '🚀',
    'agriculture': '🌾',
    'biotech': '🧬',
    'cybersecurity': '🔒',
    'blockchain': '⛓️',
    'robotics': '🦾',
    'quantum': '⚛️',
    'entertainment': '🎭',
    'media': '📺',
    'sports': '⚽',
    'transportation': '🚚',
    'hospitality': '🏨',
    'retail': '🛒',
    'real-estate': '🏠',
    'government': '🏛️',
    'public-service': '🚒',
    'military': '🎖️',
    'nonprofit': '❤️',
    'consulting': '💡',
    'hr': '👥',
    'operations': '⚙️',
    'sales': '🤝',
    'customer-service': '🎧',
    'admin': '📋',
    'facilities': '🏢',
    'environmental': '🌱',
    'safety': '🛡️',
    'quality': '✅',
    'supply-chain': '📦',
    'logistics': '🚛',
    'procurement': '🛍️',
    'events': '🎪',
    'writing': '✍️',
    'translation': '🌐',
    'interpreting': '🗣️',
    'teaching': '📚',
    'coaching': '🎯',
    'therapy': '🧠',
    'social-work': '🤲',
    'library': '📖',
    'museum': '🏛️',
    'archaeology': '⛏️',
    'architecture': '🏗️',
    'interior-design': '🛋️',
    'fashion': '👗',
    'culinary': '👨‍🍳',
    'baking': '🥖',
    'bartending': '🍸',
    'agriculture': '🚜',
    'fishing': '🎣',
    'forestry': '🌲',
    'mining': '⛏️',
    'oil-gas': '🛢️',
    'utilities': '💡',
    'waste-management': '♻️',
    'cleaning': '🧹',
    'maintenance': '🔧',
    'repair': '🛠️',
    'installation': '🔩',
    'inspection': '🔍',
    'testing': '🧪',
    'calibration': '⚖️',
    'automation': '🤖',
    'control-systems': '🎛️',
    'instrumentation': '📡',
    'telecommunications': '📡',
    'networking': '🌐',
    'cloud': '☁️',
    'devops': '🚀',
    'security-ops': '🔐',
    'database': '🗃️',
    'analytics': '📊',
    'visualization': '📈',
    'machine-learning': '🧠',
    'deep-learning': '🔮',
    'nlp': '💬',
    'computer-vision': '👁️',
    'robotics': '🦾',
    'embedded': '🔌',
    'iot': '📲',
    'hardware': '💾',
    'semiconductor': '💿',
    'optics': '🔭',
    'photonics': '✨',
    'nanotechnology': '🔬',
    'biomedical': '🏥',
    'pharmaceutical': '💊',
    'veterinary': '🐾',
    'dentistry': '🦷',
    'optometry': '👓',
    'physical-therapy': '🏃',
    'occupational-therapy': '🤲',
    'speech-therapy': '🗣️',
    'nutrition': '🥗',
    'fitness': '💪',
    'wellness': '🧘',
    'beauty': '💄',
    'spa': '🧖',
    'tourism': '✈️',
    'travel': '🌍',
    'hotel': '🏨',
    'restaurant': '🍽️',
    'catering': '🍱',
    'food-service': '🍔',
    'agriculture': '🌾',
    'horticulture': '🌷',
    'landscaping': '🌳',
    'gardening': '🌻',
    'animal-care': '🐕',
    'pet-care': '🐱',
    'veterinary': '🐾',
    'zoology': '🦁',
    'marine-biology': '🐋',
    'conservation': '🌿',
    'wildlife': '🦅',
    'forestry': '🌲',
    'fisheries': '🐟',
    'aquaculture': '🦐',
    'mining': '⛏️',
    'metallurgy': '🔩',
    'materials': '🔧',
    'ceramics': '🏺',
    'textiles': '🧵',
    'paper': '📄',
    'printing': '🖨️',
    'packaging': '📦',
    'shipping': '🚢',
    'freight': '📬',
    'warehousing': '🏭',
    'distribution': '🚚',
    'inventory': '📋',
    'purchasing': '🛒',
    'sourcing': '🌐',
    'vendor-management': '🤝',
    'contract-management': '📄',
    'project-management': '📊',
    'program-management': '📈',
    'portfolio-management': '💼',
    'change-management': '🔄',
    'risk-management': '⚠️',
    'compliance': '✅',
    'governance': '🏛️',
    'audit': '🔍',
    'forensics': '🔬',
    'investigation': '🕵️',
    'intelligence': '🧠',
    'research': '🔬',
    'development': '💡',
    'innovation': '✨',
    'design': '🎨',
    'engineering': '⚙️',
    'architecture': '🏗️',
    'planning': '📐',
    'scheduling': '📅',
    'estimating': '💰',
    'surveying': '📏',
    'mapping': '🗺️',
    'gis': '🌍',
    'remote-sensing': '🛰️',
    'photogrammetry': '📷',
    'cartography': '🗺️',
    'meteorology': '🌤️',
    'climatology': '🌡️',
    'oceanography': '🌊',
    'hydrology': '💧',
    'geology': '🪨',
    'seismology': '🌋',
    'volcanology': '🌋',
    'paleontology': '🦴',
    'anthropology': '🏺',
    'archaeology': '⛏️',
    'history': '📜',
    'philosophy': '🤔',
    'linguistics': '🗣️',
    'literature': '📚',
    'music': '🎵',
    'art': '🎨',
    'dance': '💃',
    'theater': '🎭',
    'film': '🎬',
    'photography': '📷',
    'journalism': '📰',
    'publishing': '📖',
    'broadcasting': '📡',
    'advertising': '📢',
    'public-relations': '📣',
    'marketing': '📊',
    'branding': '🏷️',
    'market-research': '📊',
    'consumer-insights': '👥',
    'product-research': '🔬',
    'usability': '👤',
    'accessibility': '♿',
    'inclusion': '🤝',
    'diversity': '🌈',
    'equity': '⚖️',
    'sustainability': '🌱',
    'csr': '❤️',
    'ethics': '⚖️',
    'legal': '⚖️',
    'regulatory': '📋',
    'policy': '📜',
    'advocacy': '📣',
    'lobbying': '🏛️',
    'diplomacy': '🕊️',
    'international-relations': '🌍',
    'trade': '💱',
    'economics': '📈',
    'finance': '💰',
    'accounting': '🧾',
    'tax': '📋',
    'insurance': '🛡️',
    'banking': '🏦',
    'investment': '📈',
    'wealth-management': '💎',
    'financial-planning': '📊',
    'credit': '💳',
    'lending': '🏦',
    'mortgage': '🏠',
    'real-estate': '🏢',
    'property-management': '🏘️',
    'facilities-management': '🏢',
    'construction-management': '🏗️',
    'site-management': '🏭',
    'safety-management': '🛡️',
    'quality-management': '✅',
    'process-improvement': '📈',
    'lean': '🏭',
    'six-sigma': '📊',
    'agile': '🔄',
    'scrum': '🏉',
    'kanban': '📋',
    'devops': '🚀',
    'sre': '🔧',
    'platform-engineering': '🏗️',
    'infrastructure': '🏭',
    'networking': '🌐',
    'telecom': '📡',
    'wireless': '📶',
    'satellite': '🛰️',
    'broadcast': '📺',
    'cable': '📡',
    'isp': '🌐',
    'datacenter': '🏢',
    'cloud': '☁️',
    'edge': '🔷',
    'cdn': '🌐',
    'hosting': '🖥️',
    'colocation': '🏢',
    'managed-services': '🔧',
    'outsourcing': '🌐',
    'consulting': '💡',
    'professional-services': '🤝',
    'staffing': '👥',
    'recruiting': '🎯',
    'hr': '👥',
    'payroll': '💰',
    'benefits': '🎁',
    'compensation': '💰',
    'performance': '📊',
    'learning': '📚',
    'development': '💡',
    'training': '🎯',
    'elearning': '💻',
    'instructional-design': '🎨',
    'curriculum': '📚',
    'assessment': '📝',
    'evaluation': '📊',
    'accreditation': '✅',
    'certification': '🏆',
    'licensing': '📜',
    'permitting': '📋',
    'inspection': '🔍',
    'testing': '🧪',
    'calibration': '⚖️',
    'metrology': '📏',
    'standardization': '📋',
    'normalization': '📊',
    'benchmarking': '📈',
    'best-practices': '⭐',
    'knowledge-management': '🧠',
    'information-management': '📊',
    'records-management': '📁',
    'archiving': '📦',
    'digitization': '💾',
    'preservation': '🏛️',
    'conservation': '🌿',
    'restoration': '🏗️',
    'maintenance': '🔧',
    'repair': '🛠️',
    'overhaul': '🔧',
    'refurbishment': '🔄',
    'remanufacturing': '🏭',
    'recycling': '♻️',
    'waste-management': '🗑️',
    'disposal': '🚮',
    'remediation': '🧹',
    'decommissioning': '🏭',
    'demolition': '🏗️',
    'abatement': '🧹',
    'mitigation': '🛡️',
    'adaptation': '🔄',
    'resilience': '💪',
    'preparedness': '🎒',
    'response': '🚨',
    'recovery': '♻️',
    'continuity': '🔁',
    'contingency': '📋',
    'emergency': '🚨',
    'crisis': '⚠️',
    'disaster': '🌪️',
    'business-continuity': '🏢',
    'it-service-management': '🔧',
    'it-asset-management': '💻',
    'software-asset-management': '💿',
    'hardware-asset-management': '💾',
    'configuration-management': '⚙️',
    'change-management': '🔄',
    'release-management': '🚀',
    'deployment-management': '📦',
    'service-desk': '🎧',
    'incident-management': '🚨',
    'problem-management': '🔍',
    'event-management': '📅',
    'availability-management': '⏱️',
    'capacity-management': '📊',
    'performance-management': '📈',
    'service-level-management': '📋',
    'vendor-management': '🤝',
    'supplier-management': '📦',
    'contract-management': '📄',
    'procurement': '🛒',
    'sourcing': '🌐',
    'purchasing': '💰',
    'logistics': '🚚',
    'transportation': '🚛',
    'warehousing': '🏭',
    'distribution': '📦',
    'fulfillment': '✅',
    'order-management': '📋',
    'inventory-management': '📊',
    'demand-planning': '📈',
    'supply-planning': '📊',
    'production-planning': '🏭',
    'master-scheduling': '📅',
    'material-requirements': '📦',
    'capacity-requirements': '📊',
    'shop-floor-control': '🏭',
    'quality-control': '✅',
    'quality-assurance': '✅',
    'inspection': '🔍',
    'testing': '🧪',
    'validation': '✅',
    'verification': '✓',
    'certification': '🏆',
    'compliance': '✅',
    'regulatory': '📋',
    'governance': '🏛️',
    'risk': '⚠️',
    'audit': '🔍',
    'control': '🎛️',
    'monitoring': '👁️',
    'reporting': '📊',
    'analytics': '📈',
    'intelligence': '🧠',
    'forecasting': '🔮',
    'predictive': '📊',
    'prescriptive': '💡',
    'optimization': '⚡',
    'simulation': '🎮',
    'modeling': '📐',
    'prototyping': '🎯',
    'experimentation': '🧪',
    'research': '🔬',
    'development': '💡',
    'innovation': '✨',
    'invention': '💡',
    'discovery': '🔍',
    'exploration': '🗺️',
    'prospecting': '⛏️',
    'surveying': '📏',
    'sampling': '🧪',
    'analysis': '🔬',
    'synthesis': '⚗️',
    'design': '🎨',
    'engineering': '⚙️',
    'manufacturing': '🏭',
    'production': '⚙️',
    'assembly': '🔧',
    'fabrication': '🏭',
    'processing': '⚙️',
    'refining': '⚗️',
    'treatment': '🧪',
    'finishing': '✨',
    'packaging': '📦',
    'labeling': '🏷️',
    'branding': '🏷️',
    'marketing': '📊',
    'sales': '💰',
    'distribution': '🚚',
    'delivery': '📦',
    'service': '🛎️',
    'support': '🎧',
    'consulting': '💡',
    'advisory': '📋',
    'coaching': '🎯',
    'mentoring': '👥',
    'training': '📚',
    'teaching': '👨‍🏫',
    'facilitating': '🤝',
    'mediating': '⚖️',
    'negotiating': '🤝',
    'arbitrating': '⚖️',
    'adjudicating': '⚖️',
    'judging': '⚖️',
    'refereeing': '📢',
    'umpiring': '📢',
    'officiating': '📢',
    'moderating': '🎤',
    'hosting': '🎭',
    'presenting': '🎤',
    'speaking': '🗣️',
    'lecturing': '👨‍🏫',
    'tutoring': '📚',
    'instructing': '📋',
    'educating': '🎓',
    'informing': '📢',
    'communicating': '💬',
    'corresponding': '✉️',
    'documenting': '📝',
    'recording': '🎙️',
    'transcribing': '📝',
    'translating': '🌐',
    'interpreting': '🗣️',
    'localizing': '🌍',
    'adapting': '🔄',
    'customizing': '⚙️',
    'personalizing': '👤',
    'configuring': '⚙️',
    'tailoring': '✂️',
    'modifying': '🔧',
    'adjusting': '🎚️',
    'tuning': '🎸',
    'calibrating': '⚖️',
    'balancing': '⚖️',
    'harmonizing': '🎵',
    'synchronizing': '⏱️',
    'coordinating': '🤝',
    'organizing': '📋',
    'planning': '📅',
    'scheduling': '📆',
    'sequencing': '🔢',
    'prioritizing': '📊',
    'ranking': '📈',
    'scoring': '🎯',
    'grading': '📝',
    'rating': '⭐',
    'reviewing': '👁️',
    'assessing': '📊',
    'evaluating': '📋',
    'appraising': '💎',
    'valuing': '💰',
    'pricing': '💵',
    'costing': '💰',
    'budgeting': '📊',
    'forecasting': '🔮',
    'projecting': '📈',
    'estimating': '💰',
    'quoting': '📋',
    'bidding': '📢',
    'tendering': '📄',
    'proposing': '💡',
    'recommending': '👍',
    'suggesting': '💡',
    'advising': '📋',
    'counseling': '🤝',
    'guiding': '🧭',
    'directing': '📢',
    'leading': '👑',
    'managing': '📊',
    'supervising': '👁️',
    'overseeing': '👁️',
    'administering': '📋',
    'operating': '⚙️',
    'running': '🏃',
    'executing': '▶️',
    'implementing': '🛠️',
    'deploying': '🚀',
    'installing': '🔧',
    'commissioning': '✅',
    'activating': '▶️',
    'launching': '🚀',
    'starting': '▶️',
    'initiating': '🚀',
    'kicking-off': '🏈',
    'opening': '🚪',
    'commencing': '🎬',
    'beginning': '🔛',
    'creating': '✨',
    'generating': '⚡',
    'producing': '🏭',
    'making': '🔨',
    'building': '🏗️',
    'constructing': '🏗️',
    'assembling': '🔧',
    'composing': '🎵',
    'formulating': '⚗️',
    'developing': '💡',
    'evolving': '🧬',
    'growing': '🌱',
    'expanding': '📈',
    'scaling': '📊',
    'multiplying': '✖️',
    'duplicating': '📄',
    'replicating': '🔁',
    'cloning': '👥',
    'copying': '📄',
    'reproducing': '🔄',
    'printing': '🖨️',
    'publishing': '📖',
    'distributing': '📦',
    'circulating': '🔄',
    'broadcasting': '📡',
    'transmitting': '📡',
    'sending': '📤',
    'shipping': '🚢',
    'transporting': '🚚',
    'moving': '📦',
    'transferring': '🔄',
    'migrating': '🐦',
    'relocating': '🚚',
    'resettling': '🏠',
    'establishing': '🏗️',
    'founding': '🏛️',
    'instituting': '🏛️',
    'constituting': '📜',
    'forming': '🎨',
    'organizing': '📋',
    'structuring': '🏗️',
    'systematizing': '⚙️',
    'standardizing': '📋',
    'normalizing': '📊',
    'routinizing': '🔄',
    'habituating': '🔄',
    'conditioning': '🧠',
    'training': '📚',
    'drilling': '🎯',
    'exercising': '🏃',
    'practicing': '🎯',
    'rehearsing': '🎭',
    'preparing': '🎒',
    'readying': '✅',
    'arranging': '📋',
    'ordering': '📊',
    'sorting': '📂',
    'classifying': '📁',
    'categorizing': '📂',
    'grouping': '👥',
    'clustering': '🔵',
    'aggregating': '➕',
    'consolidating': '🏗️',
    'integrating': '🔗',
    'unifying': '🤝',
    'merging': '🔄',
    'combining': '➕',
    'blending': '🎨',
    'mixing': '⚗️',
    'fusing': '🔥',
    'melding': '🔥',
    'welding': '🔥',
    'soldering': '🔥',
    'bonding': '🔗',
    'adhering': '🔗',
    'sticking': '🩹',
    'attaching': '📎',
    'connecting': '🔗',
    'linking': '🔗',
    'coupling': '🔗',
    'joining': '➕',
    'uniting': '🤝',
    'allying': '🤝',
    'associating': '👥',
    'affiliating': '🔗',
    'partnering': '🤝',
    'collaborating': '🤝',
    'cooperating': '🤝',
    'coordinating': '🤝',
    'synchronizing': '⏱️',
    'harmonizing': '🎵',
    'orchestrating': '🎼',
    'conducting': '🎼',
    'directing': '📢',
    'guiding': '🧭',
    'steering': '🚢',
    'piloting': '✈️',
    'navigating': '🧭',
    'driving': '🚗',
    'riding': '🏇',
    'flying': '✈️',
    'sailing': '⛵',
    'boating': '🚤',
    'rowing': '🚣',
    'paddling': '🛶',
    'swimming': '🏊',
    'diving': '🤿',
    'surfing': '🏄',
    'skiing': '⛷️',
    'skating': '⛸️',
    'boarding': '🛹',
    'hiking': '🥾',
    'climbing': '🧗',
    'camping': '⛺',
    'fishing': '🎣',
    'hunting': '🏹',
    'tracking': '👣',
    'trailing': '🛤️',
    'following': '👣',
    'pursuing': '🏃',
    'chasing': '🏃',
    'hounding': '🐕',
    'stalking': '🐆',
    'ambushing': '🌳',
    'trapping': '🪤',
    'snaring': '🕸️',
    'netting': '🕸️',
    'catching': '🎣',
    'capturing': '🎯',
    'seizing': '✊',
    'grabbing': '✊',
    'taking': '✋',
    'getting': '✅',
    'obtaining': '📋',
    'acquiring': '💰',
    'procuring': '🛒',
    'securing': '🔒',
    'gaining': '📈',
    'earning': '💰',
    'winning': '🏆',
    'achieving': '🏆',
    'accomplishing': '✅',
    'fulfilling': '✅',
    'completing': '✅',
    'finishing': '🏁',
    'concluding': '🏁',
    'closing': '🚪',
    'ending': '🏁',
    'terminating': '🛑',
    'stopping': '🛑',
    'halting': '🛑',
    'pausing': '⏸️',
    'suspending': '⏸️',
    'interrupting': '⏸️',
    'breaking': '💔',
    'disrupting': '💥',
    'disturbing': '🌊',
    'interfering': '⚡',
    'hindering': '🚧',
    'impeding': '🚧',
    'obstructing': '🚧',
    'blocking': '🚫',
    'barricading': '🚧',
    'fortifying': '🏰',
    'defending': '🛡️',
    'guarding': '💂',
    'protecting': '🛡️',
    'shielding': '🛡️',
    'screening': '📺',
    'covering': '📔',
    'hiding': '🙈',
    'concealing': '🎭',
    'masking': '🎭',
    'disguising': '🎭',
    'camouflaging': '🦎',
    'cloaking': '🧥',
    'veiling': '🧕',
    'shrouding': '🌫️',
    'wrapping': '🎁',
    'packaging': '📦',
    'boxing': '📦',
    'crating': '📦',
    'containing': '📦',
    'holding': '✋',
    'keeping': '🔒',
    'retaining': '🔒',
    'maintaining': '🔧',
    'preserving': '🏛️',
    'conserving': '🌿',
    'saving': '💾',
    'storing': '🗃️',
    'warehousing': '🏭',
    'stocking': '📦',
    'inventorying': '📋',
    'cataloging': '📚',
    'indexing': '📇',
    'filing': '📁',
    'archiving': '📦',
    'recording': '🎙️',
    'logging': '📝',
    'registering': '📝',
    'enrolling': '📝',
    'listing': '📋',
    'enumerating': '🔢',
    'counting': '🔢',
    'numbering': '🔢',
    'quantifying': '📊',
    'measuring': '📏',
    'weighing': '⚖️',
    'scaling': '📊',
    'sizing': '📏',
    'dimensioning': '📐',
    'calculating': '🧮',
    'computing': '💻',
    'processing': '⚙️',
    'analyzing': '🔬',
    'examining': '🔍',
    'inspecting': '🔍',
    'investigating': '🕵️',
    'exploring': '🔭',
    'researching': '🔬',
    'studying': '📚',
    'learning': '🧠',
    'understanding': '💡',
    'knowing': '🧠',
    'recognizing': '👁️',
    'identifying': '🏷️',
    'naming': '🏷️',
    'labeling': '🏷️',
    'tagging': '🏷️',
    'coding': '💻',
    'marking': '✏️',
    'noting': '📝',
    'annotating': '📝',
    'commenting': '💬',
    'explaining': '💬',
    'describing': '📝',
    'defining': '📖',
    'specifying': '📋',
    'detailing': '📝',
    'elaborating': '📝',
    'expanding': '📈',
    'extending': '📏',
    'stretching': '🤸',
    'reaching': '🙌',
    'grasping': '✊',
    'seizing': '✊',
    'capturing': '🎯',
    'catching': '🎣',
    'trapping': '🪤',
    'snaring': '🕸️',
    'entangling': '🕸️',
    'ensnaring': '🕸️',
    'tricking': '🎭',
    'deceiving': '🎭',
    'misleading': '🎭',
    'duping': '🎭',
    'conning': '🎭',
    'scamming': '🚫',
    'defrauding': '🚫',
    'swindling': '🚫',
    'cheating': '🚫',
    'counterfeiting': '🚫',
    'forging': '🔨',
    'faking': '🎭',
    'pretending': '🎭',
    'acting': '🎭',
    'performing': '🎭',
    'playing': '🎮',
    'simulating': '🎮',
    'emulating': '🎮',
    'imitating': '🎭',
    'mimicking': '🦜',
    'copying': '📄',
    'replicating': '🔁',
    'reproducing': '🔄',
    'cloning': '👥',
    'duplicating': '📄',
    'multiplying': '✖️',
    'increasing': '📈',
    'decreasing': '📉',
    'reducing': '📉',
    'minimizing': '⬇️',
    'maximizing': '⬆️',
    'optimizing': '⚡',
    'improving': '📈',
    'enhancing': '✨',
    'upgrading': '⬆️',
    'advancing': '🚀',
    'progressing': '📈',
    'developing': '💡',
    'evolving': '🧬',
    'maturing': '🍷',
    'growing': '🌱',
    'expanding': '📈',
    'extending': '📏',
    'broadening': '↔️',
    'widening': '↔️',
    'deepening': '⬇️',
    'heightening': '⬆️',
    'lifting': '🏋️',
    'raising': '⬆️',
    'elevating': '⬆️',
    'boosting': '🚀',
    'augmenting': '➕',
    'supplementing': '➕',
    'complementing': '➕',
    'completing': '✅',
    'perfecting': '💎',
    'polishing': '✨',
    'refining': '⚗️',
    'purifying': '💧',
    'filtering': '🗑️',
    'straining': '🗑️',
    'sieving': '🗑️',
    'sorting': '📂',
    'sifting': '🗑️',
    'screening': '📺',
    'selecting': '✓',
    'choosing': '✓',
    'picking': '✓',
    'electing': '🗳️',
    'appointing': '👔',
    'assigning': '📋',
    'delegating': '📋',
    'entrusting': '🔐',
    'empowering': '💪',
    'authorizing': '✅',
    'licensing': '📜',
    'permitting': '📋',
    'allowing': '✅',
    'enabling': '✅',
    'facilitating': '🤝',
    'helping': '🤝',
    'aiding': '🤝',
    'assisting': '🤝',
    'supporting': '🤝',
    'backing': '🤝',
    'promoting': '📢',
    'advancing': '🚀',
    'furthering': '🚀',
    'encouraging': '👍',
    'motivating': '🎯',
    'inspiring': '✨',
    'stimulating': '⚡',
    'exciting': '🎉',
    'thrilling': '🎢',
    'delighting': '😊',
    'pleasing': '😊',
    'satisfying': '✅',
    'fulfilling': '✅',
    'gratifying': '😊',
    'rewarding': '🏆',
    'compensating': '💰',
    'remunerating': '💰',
    'paying': '💰',
    'repaying': '💰',
    'reimbursing': '💰',
    'refunding': '💰',
    'rebating': '💰',
    'discounting': '🏷️',
    'deducting': '➖',
    'subtracting': '➖',
    'removing': '🗑️',
    'eliminating': '🚫',
    'eradicating': '🚫',
    'exterminating': '🚫',
    'annihilating': '💥',
    'destroying': '💥',
    'demolishing': '🏗️',
    'razing': '🏗️',
    'leveling': '🏗️',
    'flattening': '🏗️',
    'clearing': '🧹',
    'cleaning': '🧹',
    'cleansing': '🧹',
    'purging': '🧹',
    'purifying': '💧',
    'detoxifying': '💧',
    'sanitizing': '🧼',
    'sterilizing': '🔬',
    'disinfecting': '🧼',
    'fumigating': '☠️',
    'decontaminating': '🧹',
    'remediating': '🧹',
    'rehabilitating': '🏥',
    'restoring': '🏗️',
    'repairing': '🛠️',
    'fixing': '🔧',
    'mending': '🧵',
    'patching': '🩹',
    'healing': '🏥',
    'curing': '💊',
    'treating': '🏥',
    'caring': '❤️',
    'nursing': '🏥',
    'doctoring': '⚕️',
    'theraping': '🧠',
    'counseling': '🤝',
    'advising': '📋',
    'consulting': '💡',
    'guiding': '🧭',
    'leading': '👑',
    'directing': '📢',
    'managing': '📊',
    'administering': '📋',
    'governing': '🏛️',
    'ruling': '👑',
    'reigning': '👑',
    'commanding': '📢',
    'ordering': '📋',
    'dictating': '📢',
    'mandating': '📋',
    'requiring': '✅',
    'demanding': '📢',
    'requesting': '🙏',
    'asking': '❓',
    'questioning': '❓',
    'inquiring': '❓',
    'querying': '❓',
    'interrogating': '❓',
    'interviewing': '🎤',
    'surveying': '📊',
    'polling': '🗳️',
    'voting': '🗳️',
    'electing': '🗳️',
    'selecting': '✓',
    'choosing': '✓',
    'picking': '✓',
    'opting': '✓',
    'deciding': '✅',
    'determining': '✅',
    'resolving': '✅',
    'settling': '✅',
    'concluding': '🏁',
    'finalizing': '✅',
    'completing': '✅',
    'closing': '🚪',
    'finishing': '🏁',
    'ending': '🏁',
    'terminating': '🛑',
    'quitting': '🚪',
    'resigning': '📄',
    'retiring': '🏖️',
    'withdrawing': '⬅️',
    'exiting': '🚪',
    'leaving': '🚪',
    'departing': '🛫',
    'going': '🏃',
    'coming': '🏃',
    'arriving': '🛬',
    'reaching': '🙌',
    'attaining': '🏆',
    'achieving': '🏆',
    'accomplishing': '✅',
}


def parse_skill_file(skill_path: Path) -> Optional[Dict]:
    """Parse a SKILL.md file and extract metadata"""
    try:
        content = skill_path.read_text(encoding='utf-8')
        
        # Extract YAML frontmatter
        if content.startswith('---'):
            parts = content.split('---', 2)
            if len(parts) >= 3:
                yaml_content = parts[1]
                try:
                    metadata = yaml.safe_load(yaml_content)
                except:
                    metadata = {}
            else:
                metadata = {}
        else:
            metadata = {}
        
        # Extract skill info
        skill_name = skill_path.parent.name
        category = skill_path.parent.parent.name
        
        # Get description
        description = metadata.get('description', '')
        if isinstance(description, str):
            # Clean up multi-line descriptions
            description = ' '.join(description.split())
        else:
            description = f"Expert {skill_name.replace('-', ' ').title()} skill"
        
        # Truncate description
        if len(description) > 100:
            description = description[:97] + '...'
        
        # Get icon based on category
        icon = CATEGORY_ICONS.get(category, '🔧')
        
        # Generate command
        command = f"Read https://raw.githubusercontent.com/theneoai/awesome-skills/main/skills/{category}/{skill_name}/SKILL.md and install {skill_name} skill"
        
        return {
            'id': skill_name,
            'name': metadata.get('display_name', skill_name.replace('-', ' ').title()),
            'category': category,
            'icon': icon,
            'desc': description,
            'command': command
        }
    except Exception as e:
        print(f"Error parsing {skill_path}: {e}")
        return None


def generate_skills_data():
    """Generate JavaScript skills data file"""
    print("🔍 Scanning all skills...")
    
    skills = []
    skill_files = list(SKILLS_DIR.rglob('**/SKILL.md'))
    
    print(f"Found {len(skill_files)} skill files")
    
    for i, skill_file in enumerate(skill_files, 1):
        if i % 50 == 0:
            print(f"  Processed {i}/{len(skill_files)}...")
        
        skill_data = parse_skill_file(skill_file)
        if skill_data:
            skills.append(skill_data)
    
    print(f"✅ Successfully parsed {len(skills)} skills")
    
    # Generate JavaScript
    js_content = f"""// Auto-generated skills data
// Generated: {__import__('datetime').datetime.now().isoformat()}
// Total skills: {len(skills)}

const allSkills = {json.dumps(skills, indent=4, ensure_ascii=False)};

// Export for use in other scripts
if (typeof module !== 'undefined' && module.exports) {{
    module.exports = {{ allSkills }};
}}
"""
    
    # Ensure directory exists
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    
    # Write file
    OUTPUT_FILE.write_text(js_content, encoding='utf-8')
    print(f"✅ Generated: {OUTPUT_FILE}")
    
    # Print category breakdown
    categories = {}
    for skill in skills:
        cat = skill['category']
        categories[cat] = categories.get(cat, 0) + 1
    
    print("\n📊 Category breakdown:")
    for cat, count in sorted(categories.items(), key=lambda x: -x[1])[:10]:
        print(f"  {cat}: {count}")
    
    return len(skills)


if __name__ == '__main__':
    count = generate_skills_data()
    print(f"\n🎉 Successfully generated data for {count} skills!")
